services:
  - type: web
    name: clickandcare-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://clickandcare-frontend.onrender.com
      - key: ADMIN_URL
        value: https://clickandcare-admin.onrender.com

  - type: web
    name: clickandcare-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://clickandcare-backend.onrender.com
      - key: VITE_STRIPE_KEY_ID
        sync: false

  - type: web
    name: clickandcare-admin
    env: static
    plan: free
    buildCommand: cd admin && npm install && npm run build
    staticPublishPath: ./admin/dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://clickandcare-backend.onrender.com 