version: '3.8'
services:
  consumer:
    build: .
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DATABASE: "Click&Care"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION:-ap-south-1}
      SQS_PAYMENT_QUEUE_URL: ${SQS_PAYMENT_QUEUE_URL}
      SQS_NOTIFICATION_QUEUE_URL: ${SQS_NOTIFICATION_QUEUE_URL}
    restart: unless-stopped
